### ISSUE TITLE
Typing issues with dbus-next v0.8.2

### ISSUE THREAD

**Issue by ErwinSteffens** [sorrir/node-bluetooth#7]
Hi all, 

Thanks for this library. We are trying to use it, but are running into some issues with the typings of dbus-next.

Because you are using v0.8.2, which does not specify a Variant constructor we are getting errors when implementing code like this: https://github.com/sorrir/node-bluetooth/blob/master/src/uart/host-interfaces/uart-advertisement.ts#L28

I see they have fixed this in v0.9.1. Any chance you can upgrade the dependency to this version?

**Comment by QuadratClown** [comment]
Thanks for pointing that out, I'll look into it.

**Comment by QuadratClown** [comment]
I'll update it, but I just remembered I've run into that issue before, so I've implemented a workaround already:
https://github.com/sorrir/node-bluetooth/blob/master/src/core/types.ts#L19
Importing this class for now should mitigate the issues, I'll update the dbus-next version with the next release.

**Comment by ErwinSteffens** [comment]
Ah, didn't spot that one. Thanks for the quick answer!

I see you mention this in the docs: 

> While it is most likely possible to use the typescript compiler with the decorators as well, in the compilation of the package the plugin @babel/plugin-transform-typescript was used for code transpiling.

Did you have any luck with using Typescript decorators? I am running into this issue below now. I will try to figure out what is going on. 

```
/app/node_modules/dbus-next/lib/service/interface.js:158
    options.fn = descriptor.descriptor.value;
                                       ^

TypeError: Cannot read property 'value' of undefined
    at /app/node_modules/dbus-next/lib/service/interface.js:158:40
    at __decorate (/app/dist/WifiAdvertisement.js:5:110)
    at Object.<anonymous> (/app/dist/WifiAdvertisement.js:32:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/dist/WifiBluetoothServer.js:5:29)
```

**Comment by QuadratClown** [comment]
You're welcome.

Unfortunately I don't recall making the typescript compiler work (however not too much time was put into it since the babel transpilation already worked). This is most likely an issue with `dbus-next`, since their documentation suggests that they use babel as well:

```You can use the Interface class to define your interfaces. This interfaces uses the proposed decorators syntax which is not yet part of the ECMAScript standard, but should be included one day. Unfortunately, you'll need a Babel plugin to make this code work for now.```

(see https://github.com/dbusjs/node-dbus-next)

**Comment by ErwinSteffens** [comment]
Yeah, just read this. I will try it out.

**Comment by QuadratClown** [comment]
Thank you. Opened a new issue for this (see #8). If you manage to get it to work or dig deeper into it, I would appreciate if you could post your progress there.

**Comment by QuadratClown** [comment]
This is issue is very old, but I've updated the `dbus-next` version to 0.10.2, which should resolve the issue. Closed for now.
